version: "2"

services:
  cuckoo:
    build:
      dockerfile: vbox/Dockerfile
      context: .
      args:
        - CUCKOO_UID=1000
    command: daemon
    ports:
        - "2042:2042"
    volumes:
      # Config
      - ./cuckoo-tmp/:/tmp/cuckoo-tmp-cuckoo/
      - ./cuckoo-storage/:/cuckoo/storage/
      - ./vbox/conf/:/cuckoo/conf/
      # - ./vbox/conf/domain.txt:/cuckoo/whitelist/domain.txt
      # Patch
      - ./patch/machine.py:/usr/lib/python2.7/site-packages/remotevbox/machine.py
      - ./patch/resultserver.py:/usr/lib/python2.7/site-packages/cuckoo/core/resultserver.py
        # Upgrade
      - ./upgrade/ie.py:/cuckoo/analyzer/windows/modules/packages/ie.py
      - ./upgrade/doc.py:/cuckoo/analyzer/windows/modules/packages/doc.py
      - ./upgrade/xls.py:/cuckoo/analyzer/windows/modules/packages/xls.py
    env_file:
      - ./vbox/config-file.env

  web:
    build:
      dockerfile: vbox/Dockerfile
      context: .
      args:
        - CUCKOO_UID=1000
    ports:
      - "80:31337"
    depends_on:
      - mongo
      - elasticsearch
      - postgres
      - cuckoo
    command: web
    volumes:
      - ./cuckoo-tmp/:/tmp/cuckoo-tmp-cuckoo/
      - ./cuckoo-storage/:/cuckoo/storage/
      - ./vbox/conf/:/cuckoo/conf/
    env_file:
      - ./vbox/config-file.env

  api:
    depends_on:
      - postgres
      - cuckoo
    build:
      dockerfile: vbox/Dockerfile
      context: .
      args:
        - CUCKOO_UID=1000
    command: api
    volumes:
      - ./cuckoo-tmp/:/tmp/cuckoo-tmp-cuckoo/
      - ./cuckoo-storage/:/cuckoo/storage/
      - ./vbox/conf/:/cuckoo/conf/
    env_file:
      - ./vbox/config-file.env

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

  elasticsearch:
    image: blacktop/elasticsearch:5.6
    ports:
      - 9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cuckoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata

volumes:
  mongo-data:
  es-data:
  postgres-data:
